/***************************************************************
* Class Name : CH_csvDownloadCtrlTest	test
* Created Date: 28 March 2020
* Description : Test class for CH_csvDownloadCtrlTest
***************************************************************/

@isTest
public class CH_csvDownloadCtrlTest {
	@isTest
	public static void fetchCase(){
 	
	Test.startTest();
		CH_csvDownloadCtrl.fetchCase();
	Test.stopTest();
	
	}
	
}