/****************************************
* Name : DS_ExecutiveTest
* Author : Accenture
* Description : Test class for DS_ExecutiveSummary.
*****************************************/
@isTest(seeAllData=true)
public class DigitalSalesPortalTileTest {

	
	/******************************
	*Method Name: test
	*Description: Test Method to cover OpportunityTriggerHelper class
	********************************/
	static testMethod void getTilesTest(){
	  
	   DigitalSalesPortalTile.getTiles();
	   
	   
	}
}