public with sharing class HWS_Constants {
	public static final String LEGAL_ENTITY = 'Legal_Entity'; 
	public static final String CUSTOMER = 'Customer';
	public static final String HWS_ADVANCE_EXCHANGE_IN_DAYS = 'HWS_Advance_Exchange_In_Days';
	public static final String HWS_ADVANCE_EXCHANGE_IN_HOURS = 'HWS_Advance_Exchange_In_Hours';
	public static final String HWS_PARENT_CASE = 'HWS_Parent_Case';
	public static final String SALES_PRODUCT = 'NokiaCPQ_Sales_Product';
	public static final String HWS_CHILD_CASE_READ_ONLY = 'HWS_Child_Case_Read_Only';
	public static final String HWS_PARENT_CASE_READ_ONLY = 'HWS_Parent_Case_Ready_Only';
	public static final String HWS_SPS_PART_SALES = 'HWS_Spare_Part_Sales'; 
	public static final String HWS_RETURN_FOR_REPAIR ='HWS_Return_For_Repair';
	public static final String HWS_SPS_PART_SALES_READ_ONLY = 'HWS_Spare_Part_Sales_Read_only';
	public static final String LOGISTIC_ACCOUNT_EXISTING = 'Logistic_Account';
	public static final String HWS_ESCALATION_CASE = 'HWS_Case_Escalation';
	public static final String PUMA1_SOURCE = 'PUMA1';
	public static final String PUMA2_SOURCE = 'PUMA2';

	//testmethod for code coverage
	public static void hwsConstantsmethod(){
		
	}
}